### ISSUE TITLE
Legacy Material WARN in Console

### ISSUE THREAD

**Issue by ghost** [Qveshn/LightAPI#15]
When starting the server this message appears:
`[21:39:22] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug
[21:39:24] [Server thread/WARN]: Legacy plugin LightAPI v3.4.3 does not specify an api-version.`

The Spigot page says it's for 1.8-1.15, so this shouldn't appear on 1.15.2?

**Comment by LOOHP** [comment]
That should be normal. Any plugin that doesn't have api-version specified in plugins.yml will cause this message to appear. Doesn't mean it isn't made from modern versions.

**Comment by ghost** [comment]
Is there any reason not to specify an `api-version`?

**Comment by LOOHP** [comment]
Before 1.13, the api version option doesn't exist, so I guess the thing is that there isn't a reason to add the setting as LightAPI doesn't deals with Materials anyway.

**Comment by Qveshn** [comment]
yes, I will add api-version
Versions prior to 1.13 should also work correctly
I will set it to 1.13. That should be enough for 1.13 and above versions

**Comment by ghost** [comment]
Thanks! 👍

**Comment by Qveshn** [comment]
Added 57d0276676a6ae0b19029602d49f28d1030768f8
