### ISSUE TITLE
1.16 support

### ISSUE THREAD

**Issue by bobhenl** [Qveshn/LightAPI#16]
Please add 1.16 support

**Comment by Qveshn** [comment]
Yes I should do it. May be at this weekend.
I hope the mechanics of light have not changed much in 1.16

**Comment by bobhenl** [comment]
Ok, try it this weekend please @Qveshn , its needed for InteractionVisualizier plugin

**Comment by Qveshn** [comment]
Done 57d0276676a6ae0b19029602d49f28d1030768f8
