### ISSUE TITLE
Lighting only updates after a server restart

### ISSUE THREAD

**Issue by Zenya4** [Qveshn/LightAPI#25]
I'm not sure if this is intended behaviour or a bug, but lighting created via `LightAPI.createLight()` only appears after a server restart. Relogging or reloading the chunk does not update the lighting in any way. Using spigot 1.16.4

**Comment by Qveshn** [comment]
Hi
Methods createLight/deleteLight creates/deletes lights only on server! Player (client) will not see changes until light-chunk-info is updated on client side. So, you should collect all chunk sections (16x16x16) that have changes after creating/deleting light on server and call updateChunk method to notify nearby players to reload light data for each section (chunk)

Try next example to set light.This code is only to learn how to use api. It is not optimized for a lot of sets at one time, but it completely sets the light and updates the chunks on the client (sends notification to client to make him update chunks) for one block position.

```java
import ru.beykerykt.lightapi.LightType;
import ru.beykerykt.lightapi.LightAPI;
...
void setLight(Location location, int lightLevel, LightType lightType) {
    Block block = location.getBlock();
    int oldLightLevel = lightType == LightType.BLOCK ? block.getLightFromBlocks() : block.getLightFromSky();
    if (oldLightLevel != lightLevel) {
        if (lightLevel > 0) {
            LightAPI.createLight(location, lightType, lightLevel, false);
        } else {
            LightAPI.deleteLight(location, lightType, false);
        }
        for (ChunkInfo chunkInfo : LightAPI.collectChunks(location, lightType, Math.max(lightLevel, oldLightLevel))) {
            LightAPI.updateChunk(chunkInfo, lightType);
        }
    }
}
```

**Comment by Zenya4** [comment]
Ok, I see. Thank you for the info. A suggestion would be to maybe include this as a built in method in the API as collectChunks() and updateChunks() doesn’t seem to be well documented on the original spigot page. Thanks for your help!
