### ISSUE TITLE
Build for 3.2.5

### ISSUE THREAD

**Issue by GuillaumeASSIER** [Qveshn/LightAPI#3]
Could you released a build for 3.2.5 please.

**Comment by Qveshn** [comment]
3.2.4-X.12.0 and 3.2.5 are the same versions.
[https://www.spigotmc.org/threads/lightapi.52691/page-6#post-2842184](url)
What reason to release new one without changes?
When I release 3.2.6, I will post it there to let people know

**Comment by GuillaumeASSIER** [comment]
OK sorry, I haven't see this commentary before.
