### ISSUE TITLE
Can someone give plugin?

### ISSUE THREAD

**Issue by Timtaran** [Qveshn/LightAPI#34]
Sorry I am lazy, can someone give me a plugin for light api :D

**Comment by 100petr** [comment]
https://github.com/Qveshn/LightAPI/releases/download/3.5.2/LightAPI-fork-3.5.2.jar

**Comment by Timtaran** [comment]
Wait, really ?
._.

**Comment by 100petr** [comment]
You wanted a download link, didn't you? Or how was the question meant?

**Comment by Qveshn** [comment]
Here is an example of some plugins that use it:
- GitHub: https://github.com/Qveshn/ShinyItems
Spigot: https://www.spigotmc.org/resources/%E2%98%85shinyitems%E2%98%85-fork.69716/
- GitHub: https://github.com/LOOHP/InteractionVisualizer
Spigot: https://www.spigotmc.org/resources/interactionvisualizer-visualize-function-blocks-entities-like-crafting-tables-with-animations.77050/
- GitHub: https://github.com/Ste3et/FurnitureLib
Spigot: https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/
- ...
