### ISSUE TITLE
Standard message

### ISSUE THREAD

**Issue by SlimeDog** [Qveshn/LightAPI#7]
LightAPI 3.4.0

Please change this
```
[12:18:08] [Server thread/INFO]: <LightAPI>: Loading handler for Spigot git-Spigot-94af569-6ddeb98 (MC: 1.14.4)
```
 to standard message format
```
[12:18:08] [Server thread/INFO]: [LightAPI] Loading handler for Spigot git-Spigot-94af569-6ddeb98 (MC: 1.14.4)
```

**Comment by Qveshn** [comment]
I agree. Time to correct messages. Not only parentheses, but also urls and so on.

Specifically on this message above, do you think to fix only parentheses or remove colors too?
In other words, use "CommandSender.sendMessage" (as done now) or use a standard bukkit logger without any colors ("Bukkit.getLogger().info")?

**Comment by SlimeDog** [comment]
I have no opinion as to the correct method. I want only that I have the option to remove formatting.

Strictly speaking, <> are angle brackets. Parentheses are (). The standard for console/log messages is square brackets [].

**Comment by Qveshn** [comment]
yes, yes, my poor english assumes: parentheses = square brackets :D
Of course I will change <> to []

Should I also remove colors in this message?

**Comment by SlimeDog** [comment]
I would like the option of no formatting: no colors, no embolden, etc. However, others like the formatting. So it should be an option, or a customizable string.

**Comment by Qveshn** [comment]
ok

**Comment by Qveshn** [comment]
Hi
I have made changes in 3.4.1
config.yml now has parameter "colored-log" (default = true)
To see it pls recreate config.yml by deleting it and restarting server/plugin
Notes: "colored-log" affects only logging and not general messages to player/console
There are not a lot of logging (mostly at plugin start). 
Is 3.4.1 what you expected?

PS. There is also additional parameter "message-prefix" (default=""). It is used as prefix before any output to players/console (command respone)

**Comment by SlimeDog** [comment]
Yes, I got it last night. It looks good.

Please build config.yml into the JAR. It is much preferable to
- unzip the JAR
- compare the current with the new config.yml
- make the necessary changes to reflect the new stuff
- re-start the server

than
- delete current config.yml
- create the new one (on start-up)
- stop the server
- make changes to reflect my edits
- re-start the server

Alternatively, document it (up-to-date) so I can copy it and see the changes. I prefer the first method.

**Comment by Qveshn** [comment]
ok

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
